-   repo: git@github.com:pre-commit/mirrors-scss-lint
    sha: d7266131da322d6d76a18d6a3659f21025d9ea11
    hooks:
    -   id: scss-lint
        files: scss/.*\.scss$
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: c94b2087dba92f9111277ded435dea9473356cae
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
-   repo: git@github.com:pre-commit/pre-commit
    sha: b136679abbd9b02e1a5f168d43341b9fe88718b3
    hooks:
    -   id: validate_config
