-   repo: git@github.com:pre-commit/mirrors-scss-lint
    sha: d7266131da322d6d76a18d6a3659f21025d9ea11
    hooks:
    -   id: scss-lint
        files: scss/.*\.scss$
        language_version: 1.9.3-p484
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: d3db0385825d4c082bc7117c090ac16cb4840f3e
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: ['-i']
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
