-   repo: http://github.com/pre-commit/mirrors-scss-lint
    sha: d7266131da322d6d76a18d6a3659f21025d9ea11
    hooks:
    -   id: scss-lint
        files: scss/.*\.scss$
-   repo: http://github.com/pre-commit/pre-commit-hooks
    sha: 7ec485352199e02d608198b0206b0675fa84af73
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
-   repo: git@github.com:pre-commit/pre-commit
    sha: e2d2c17218e7e40a44ab32c522cdd4169a9da5cd
    hooks:
    -   id: validate_config
