-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.5
    -   id: end-of-file-fixer
        language_version: python3.5
    -   id: autopep8-wrapper
        language_version: python3.5
    -   id: check-yaml
        language_version: python3.5
    -   id: debug-statements
        language_version: python3.5
    -   id: flake8
        language_version: python3.5
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.4
    hooks:
    -   id: reorder-python-imports
        language_version: python3.5
-   repo: local
    hooks:
    -   id: scss-lint
        name: scss-lint
        entry: scss-lint
        types: [scss]
        language: ruby
        language_version: 2.1.5
        additional_dependencies: ['scss_lint:0.52.0']
