-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: local
    hooks:
    -   id: scss-lint
        name: scss-lint
        entry: scss-lint
        types: [scss]
        language: ruby
        additional_dependencies: ['scss_lint:0.57.0']
    -   id: no-github-dot-git
        name: No need for .git for github urls
        entry: 'github.*\.git'
        files: all-repos.yaml
        language: pygrep
