-   repo: git@github.com:pre-commit/mirrors-scss-lint
    sha: 3eb13b9647543ad4d6a62c8be8a9131e3b99b96a
    hooks:
    -   id: scss-lint
        files: scss/.*\.scss$
        language_version: 1.9.3-p484
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
