-   repo: git@github.com:pre-commit/mirrors-scss-lint
    sha: v0.52.0
    hooks:
    -   id: scss-lint
        language_version: 2.1.2
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v0.7.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3.5
    -   id: end-of-file-fixer
        language_version: python3.5
    -   id: autopep8-wrapper
        language_version: python3.5
    -   id: check-yaml
        language_version: python3.5
    -   id: debug-statements
        language_version: python3.5
    -   id: flake8
        language_version: python3.5
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3.5
