language: python
python:
  - "2.7"
script: make
branches:
  except:
    - master
env:
  global:
    - GH_REF: github.com/pre-commit/pre-commit.github.io.git
    # GH_TOKEN
    - secure: nNgNYmtwXquPRuAFi/6kXOVjSYroglxuIjvZHDun5eCYikV1KgvXM1Q9Yh3CWgNmIWG1LKt76nt/5u4tLleJiZ7AbjcmLMb9dw7679jFNaDd14tIGyWyYBzrqfqxnayTNLclcfp59l0Yi3ag1i7z4J94LM+7tp8D4jr7RyLd++I=
after_success:
  - bash push_to_gh.sh
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
